# Generated by Django 5.1.7 on 2025-04-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donor_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Transferred", "Transferred"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("payment_reference", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Donation",
                "verbose_name_plural": "Donations",
            },
        ),
        migrations.RemoveField(
            model_name="fundallocation",
            name="donor",
        ),
        migrations.DeleteModel(
            name="Donor",
        ),
    ]
