# Generated by Django 5.2 on 2025-04-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "amount_requested",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("description", models.TextField(help_text="Purpose of the funding")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Declined", "Declined"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("date_requested", models.DateTimeField(auto_now_add=True)),
                ("date_processed", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
