# Generated by Django 5.2 on 2025-04-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0002_fundrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundrequest",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
