# Generated by Django 5.1.7 on 2025-04-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0003_fundrequest_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Transferred", "Transferred"),
                    ("Failed", "Failed"),
                    ("Successful", "Successful"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
